### PR TITLE
Add contract

### PR DESCRIPTION
**Pull request by roman-mazur**
The minimal first version to start working on deploys from the product repo.

Change-type: patch
Signed-off-by: Roman Mazur <roman@balena.io>

### CODE REVIEW

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by roman-mazur** [comment]
@balena-ci retest please

**Comment by nazrhom** [comment]
@roman-mazur LGTM do we have node >= 12 as a dependency?

**Pull request merged**
